import type { Metadata } from "next";
import { Geist, Geist_Mono, Raleway } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import SmoothScrollProvider, { ClientProviders } from "./providers";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AutoML Studio - Train models with flow",
  description: "Generated by create next app",
  icons: {
    icon: "/favicons/web/icons8-workflow-isometric-line-32.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${raleway.variable} ${geistSans.variable} ${geistMono.variable} antialiased dark bg-radial from-primary/20 dark:via-black dark:to-black`}
      >
        {/* <ThemeProvider defaultTheme="system" attribute="class" enableSystem> */}

        <SmoothScrollProvider>
          <ClientProviders>{children}</ClientProviders>
        </SmoothScrollProvider>
        <Toaster />
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
